name: Ejecutar Scrapers y Actualizar API

on:
  schedule:
    - cron: '0 * * * *' # Corre cada hora
  workflow_dispatch: # Permite ejecución manual si lo necesitas

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    steps:
    # Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Instalar Python y dependencias
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ejecutar los scrapers
    - name: Ejecutacion de scrapers
      run: |
        python HM.py
        python KOAJ.py
        python PULLBEAR.py
        # Asumiendo que los scrapers guardan resultados en `data.json`

    # Ejecutar proceso ETL
    - name: Se ejecuta ETL
      run: |
        python etl.py
        # ETL genera el archivo final: `result.json`

    # Subir datos a MockAPI
    - name: Update MockAPI
      env:
        MOCKAPI_URL: ${{ secrets.MOCKAPI_URL }}
      run: |
        curl -X DELETE $MOCKAPI_URL
        curl -X POST -H "Content-Type: application/json" -d @camisas_unificadas.json $MOCKAPI_URL
